version: '3.8'

services:
  database:
    container_name: database_challenge
    image: postgres:13.0-alpine
    env_file: 
      - ./.env
    volumes:
      - ./DB:/var/lib/postgresql/data/
    restart: always
  web:
    container_name: web_challenge
    build: .
    command: ["/bin/sh", "./scripts/runserver.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
